# alias
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='colordiff'
alias tree='tree -C'
alias ls='ls -F --color=auto'
alias ll='ls -lh'
alias la='ls -a'
alias exa='exa -F --color=auto'
alias exal='exa -lh'
alias exaa='exa -a'
# alias ls='exa'
# alias cat='bat'
# alias find='fd'
