add_newline = false
format = """
$all\
$fill\
$line_break\
$jobs\
$battery\
$status\
$shell\
$character"""
right_format = """
$time"""

[fill]
symbol = "--"
style = "bold purple"
disabled = false

[directory]
truncation_length = 0
truncate_to_repo = false

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold yellow"

[[battery.display]]
threshold = 80
style = "bold green"

[[battery.display]]
threshold = 100
style = "bold cyan"

# RPROMPT

[time]
disabled = false
time_format = "%F %T"
