name: MacOS-Test

on:
  push:
  workflow_dispatch:

jobs:
  MacOS:
    runs-on: macos-latest
    defaults:
      run:
        shell: zsh {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Without error
        run: sed -i.bak -e "/mas /d" .settings/homebrew/Brewfile

      - name: Run 'brew update'
        run: brew update

      - name: Test install.sh
        run: |
          export SHELL="/bin/zsh"
          ./install.sh

      - name: Test zsh
        run: |
          export SHELL="/bin/zsh"
          exec zsh -i -c "exit"

      - name: Test install.sh again
        run: |
          export SHELL="/bin/zsh"
          ./install.sh

      - name: Test zsh again
        run: |
          export SHELL="/bin/zsh"
          exec zsh -i -c "exit"
