name: MacOS-Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  MacOS:
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: |
          sed -i.bak -e '/mas /d' .settings/homebrew/Brewfile
          ./install.sh
