name: MacOS-Test

on: [ workflow_dispatch ]

jobs:
  MacOS:
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Without error
        run: sed -i.bak -e "/mas /d" -e "/playcover/d" .settings/homebrew/Brewfile

      - name: Test
        run: ./install.sh
