name: MacOS-Test

on:
  push:
  workflow_dispatch:

jobs:
  MacOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Without error
        run: sed -i.bak -e "/mas /d" -e "/playcover/d" .settings/homebrew/Brewfile

      - name: Test install.sh
        run: ./install.sh

      - name: Test zsh
        run: exec zsh -l -c "exit 0"
