name: MacOS-Test

on:
  push:
  workflow_dispatch:

jobs:
  MacOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Without error
        run: sed -i.bak -e "/mas /d" .settings/homebrew/Brewfile

      - name: Test install.sh
        run: |
          export SHELL="/bin/zsh"
          ./install.sh
        shell: zsh {0}

      - name: Test zsh
        run: |
          export SHELL="/bin/zsh"
          exec zsh -i -c "exit"
        shell: zsh {0}

      - name: Test install.sh again
        run: |
          export SHELL="/bin/zsh"
          ./install.sh
        shell: zsh {0}

      - name: Test zsh again
        run: |
          export SHELL="/bin/zsh"
          exec zsh -i -c "exit"
        shell: zsh {0}
