name: test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Ubuntu
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: |
          ./install.sh

  # MacOS
  MacOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
