name: test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Ubuntu
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: |
          sudo apt update
          sudo apt install -y zsh
          echo "
          _APTMGR = apt
          DOWNLOADBEFORE = true
          " | sudo tee /etc/apt-fast.conf > /dev/null
          ./install.sh

  # MacOS
  MacOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
