name: Ubuntu-Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: |
          sudo apt update
          sudo apt install -y zsh
          ./install.sh
