name: Ubuntu-Test

on:
  push:
  workflow_dispatch:

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Without error
        run: sed -i.bak -e "/winehq/d" install/apt.sh

      - name: Test
        run: ./install.sh
