name: Ubuntu-Test

on:
  push:
  workflow_dispatch:

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install zsh
        run: |
          sudo apt update
          sudo apt install -y zsh

      - name: Change default shell
        run: |
          chsh -s /bin/zsh
          exit

      - name: Without error
        run: sed -i.bak -e "/winehq/d" install/apt.sh

      - name: Test install.sh
        run: ./install.sh

      - name: Test zsh
        run: exec zsh -i -c "exit"

      - name: Test install.sh again
        run: ./install.sh

      - name: Test zsh again
        run: exec zsh -i -c "exit"
