name: Ubuntu-Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: |
          sudo apt update
          sudo apt install -y zsh
          sed -i.bak '/winehq/d' apt.sh
          ./install.sh
